version: '3'
services:
  bull-monitor:
    image: ejhayes/nodejs-bull-monitor:latest
    ports:
      - 3001:3000
    environment:
      REDIS_HOST: host.docker.internal
      REDIS_PORT: 6379
      BULL_WATCH_QUEUE_PREFIXES: bull
      PORT: 3000
      UI: bull-master
