version: "3"
services:
    container_name: ${CONTAINER_NAME}
    image: postgis/postgis:14-3.2
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}
      timeout: 45s
      interval: 10s
      retries: 10
    redis:
      image: redis:latest
      ports:
        - "6379:6379"
volumes:
  postgres: ~
