version: '3'
services:
  db:
    container_name: ${CONTAINER_NAME}
    image: postgis/postgis:14-3.2
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres:/var/lib/postgresql/data

  # Disable for now, not used much and will run faster
  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
  #     - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
  #   ports:
  #     - "5050:80"

  redis:
    image: redis:latest
    ports:
      - '6389:6379'
volumes:
  postgres: ~
